name: Giant Specials to Google Sheets

on:
  schedule:
    # Example: Tue & Fri 09:30 America/New_York ≈ 13:30 UTC during EDT; adjust as needed
    - cron: "30 13 * * 2,5"
  workflow_dispatch: {}

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/service_account.json

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo listing (sanity check)
        run: ls -la

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers (with OS deps)
        run: |
          python -m playwright install --with-deps chromium

      # >>> THIS IS THE IMPORTANT PART: materialize the JSON key safely
      - name: Write service account key from base64
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_B64 }}" | base64 -d > "$GOOGLE_APPLICATION_CREDENTIALS"
          python - <<'PY'
import json,os,sys
p=os.environ["GOOGLE_APPLICATION_CREDENTIALS"]
try:
    with open(p) as f: json.load(f)
    print("[INFO] service_account.json looks valid.")
except Exception as e:
    print("[ERROR] service_account.json invalid:", e); sys.exit(1)
PY

      - name: Run scraper (unbuffered to flush logs)
        run: |
          python -u giant_specials_to_sheets.py

      # Always collect artifacts for debugging (CSV/XLSX when it works, screenshots/HTML if not)
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scraper-run
          path: |
            *.csv
            *.xlsx
            page.png
            page.html
          if-no-files-found: ignore
